### ISSUE TITLE
Align login button

### ISSUE THREAD

**Issue by SiddharthSham** [SiddharthSham/QuestionBank-Hackathon#11]
Move login button slightly to the left. Current placement is inconsistent with padding.
(Maybe an issue across different displays?)

![screenshot 5](https://user-images.githubusercontent.com/9303607/33646597-602600ee-da76-11e7-9d62-5dfb6514e222.png)

**Comment by sanjaytharagesh31** [comment]
I've made some modifications in log-in button alignment. Have a look :-)

**Comment by SiddharthSham** [comment]
Seems to be fixed. I'm closing the issue, for now. Have to check across different displays though.
